version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'dusk-team'
    auto-merge:
      enabled: true
      allowed-versions:
        - '*'
      commit-message:
        prefix: 'chore'
        prefix-development: 'chore'
        include: 'scope'
    allow:
      - dependency-type: 'direct'
    groups:
      dev-dependencies:
        patterns:
          - '*'
    versioning-strategy: increase

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'dusk-team'
    auto-merge:
      enabled: true
      commit-message:
        prefix: 'chore'
        prefix-development: 'chore'
        include: 'scope'
